//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimsProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimsProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Није пронађен ни један смештај..
        /// </summary>
        internal static string AAE {
            get {
                return ResourceManager.GetString("AAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поштовање Правила.
        /// </summary>
        internal static string AbidingByTheRules {
            get {
                return ResourceManager.GetString("AbidingByTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назив Смештаја:.
        /// </summary>
        internal static string AccommodationName {
            get {
                return ResourceManager.GetString("AccommodationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип Смештаја:.
        /// </summary>
        internal static string AccommodationType {
            get {
                return ResourceManager.GetString("AccommodationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додај Слике.
        /// </summary>
        internal static string AddImages {
            get {
                return ResourceManager.GetString("AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додатни Коментар.
        /// </summary>
        internal static string AdditionalComment {
            get {
                return ResourceManager.GetString("AdditionalComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назив Смештаја.
        /// </summary>
        internal static string AName {
            get {
                return ResourceManager.GetString("AName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додај Нови Коментар:.
        /// </summary>
        internal static string ANC {
            get {
                return ResourceManager.GetString("ANC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Било Који.
        /// </summary>
        internal static string Any {
            get {
                return ResourceManager.GetString("Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Било Која.
        /// </summary>
        internal static string AnyF {
            get {
                return ResourceManager.GetString("AnyF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Било Где, Било Кад.
        /// </summary>
        internal static string AnywhereAnytime {
            get {
                return ResourceManager.GetString("AnywhereAnytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Било Где, Било Кад (F7).
        /// </summary>
        internal static string AnywhereAnytimeF {
            get {
                return ResourceManager.GetString("AnywhereAnytimeF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум Доласка и Одласка:.
        /// </summary>
        internal static string ArrivalAndCheckoutDate {
            get {
                return ResourceManager.GetString("ArrivalAndCheckoutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум Доласка.
        /// </summary>
        internal static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опсег Датума Доласка:.
        /// </summary>
        internal static string ArrivalDateRange {
            get {
                return ResourceManager.GetString("ArrivalDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположиви Дани.
        /// </summary>
        internal static string AvailableDates {
            get {
                return ResourceManager.GetString("AvailableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступно За Оценити.
        /// </summary>
        internal static string AvailableToReview {
            get {
                return ResourceManager.GetString("AvailableToReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да ли сте сигурни да се желите одјавити?.
        /// </summary>
        internal static string AYL {
            get {
                return ResourceManager.GetString("AYL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да ли сте сигурни да желите да резервишете:.
        /// </summary>
        internal static string AYS {
            get {
                return ResourceManager.GetString("AYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апликација За Резервацију.
        /// </summary>
        internal static string BA {
            get {
                return ResourceManager.GetString("BA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказано..
        /// </summary>
        internal static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Откажи Резервацију (F1).
        /// </summary>
        internal static string CancelReservationF {
            get {
                return ResourceManager.GetString("CancelReservationF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени Језик (F11).
        /// </summary>
        internal static string ChangeLanguageF {
            get {
                return ResourceManager.GetString("ChangeLanguageF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени Тему (F10).
        /// </summary>
        internal static string ChangeThemeF {
            get {
                return ResourceManager.GetString("ChangeThemeF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум Одласка.
        /// </summary>
        internal static string CheckoutDate {
            get {
                return ResourceManager.GetString("CheckoutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистоћа.
        /// </summary>
        internal static string Cleanliness {
            get {
                return ResourceManager.GetString("Cleanliness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистоћа:.
        /// </summary>
        internal static string CleanlinessD {
            get {
                return ResourceManager.GetString("CleanlinessD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказане Резервације.
        /// </summary>
        internal static string CncCb {
            get {
                return ResourceManager.GetString("CncCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментар.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментари:.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потврда.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Држава и Град:.
        /// </summary>
        internal static string CountryAndCity {
            get {
                return ResourceManager.GetString("CountryAndCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментар пријављен.
        /// </summary>
        internal static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Покрени Форум (F1).
        /// </summary>
        internal static string CreateForumF {
            get {
                return ResourceManager.GetString("CreateForumF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвори Нови Форум.
        /// </summary>
        internal static string CreateNewForum {
            get {
                return ResourceManager.GetString("CreateNewForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опсег Датума:.
        /// </summary>
        internal static string DateRangeOpt {
            get {
                return ResourceManager.GetString("DateRangeOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затвори Форум (CTRL+F2).
        /// </summary>
        internal static string DeleteForumF {
            get {
                return ResourceManager.GetString("DeleteForumF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дужина боравка мора бити број.
        /// </summary>
        internal static string ERR1 {
            get {
                return ResourceManager.GetString("ERR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број гостију је преко макс .
        /// </summary>
        internal static string ERR10 {
            get {
                return ResourceManager.GetString("ERR10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дужина боравка је обавезна.
        /// </summary>
        internal static string ERR2 {
            get {
                return ResourceManager.GetString("ERR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број гостију мора бити број.
        /// </summary>
        internal static string ERR3 {
            get {
                return ResourceManager.GetString("ERR3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број гостију је обавезан.
        /// </summary>
        internal static string ERR4 {
            get {
                return ResourceManager.GetString("ERR4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сме бити у прошлости.
        /// </summary>
        internal static string ERR5 {
            get {
                return ResourceManager.GetString("ERR5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датуми нису по реду.
        /// </summary>
        internal static string ERR6 {
            get {
                return ResourceManager.GetString("ERR6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментар је обавезан.
        /// </summary>
        internal static string ERR7 {
            get {
                return ResourceManager.GetString("ERR7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум је обавезан.
        /// </summary>
        internal static string ERR8 {
            get {
                return ResourceManager.GetString("ERR8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дужина боравка је испод мин .
        /// </summary>
        internal static string ERR9 {
            get {
                return ResourceManager.GetString("ERR9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грешка при додавању слике..
        /// </summary>
        internal static string ErrorAddingImage {
            get {
                return ResourceManager.GetString("ErrorAddingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поштовање Правила.
        /// </summary>
        internal static string FollowingTheRules {
            get {
                return ResourceManager.GetString("FollowingTheRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форуми.
        /// </summary>
        internal static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Форуми (F8).
        /// </summary>
        internal static string ForumsF {
            get {
                return ResourceManager.GetString("ForumsF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to од.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генериши (F1).
        /// </summary>
        internal static string GenerateF {
            get {
                return ResourceManager.GetString("GenerateF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генериши ПДФ Извештај.
        /// </summary>
        internal static string GeneratePDF {
            get {
                return ResourceManager.GetString("GeneratePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад (ESC).
        /// </summary>
        internal static string GoBackF {
            get {
                return ResourceManager.GetString("GoBackF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил (F3).
        /// </summary>
        internal static string GuestProfileF {
            get {
                return ResourceManager.GetString("GuestProfileF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARROWS - Навигација кроз табеле или комбобокс.
        /// </summary>
        internal static string HelpA {
            get {
                return ResourceManager.GetString("HelpA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC - Затвара тренутни прозор/страницу.
        /// </summary>
        internal static string HelpE {
            get {
                return ResourceManager.GetString("HelpE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помоћ (F9).
        /// </summary>
        internal static string HelpF {
            get {
                return ResourceManager.GetString("HelpF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иконица показује да ли је корисник био на локацији.
        /// </summary>
        internal static string HelpL {
            get {
                return ResourceManager.GetString("HelpL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER - Отвара преглед слика за одабрани смештај.
        /// </summary>
        internal static string HelpR {
            get {
                return ResourceManager.GetString("HelpR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT-TAB - Пролаз кроз контроле уназад.
        /// </summary>
        internal static string HelpS {
            get {
                return ResourceManager.GetString("HelpS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAB - Пролаз кроз контроле.
        /// </summary>
        internal static string HelpT {
            get {
                return ResourceManager.GetString("HelpT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помоћ.
        /// </summary>
        internal static string HelpW {
            get {
                return ResourceManager.GetString("HelpW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Иконица показује да ли је форум веома користан.
        /// </summary>
        internal static string HelpZ {
            get {
                return ResourceManager.GetString("HelpZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слика.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед Слика.
        /// </summary>
        internal static string ImageViewer {
            get {
                return ResourceManager.GetString("ImageViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Унеси Нове Датуме.
        /// </summary>
        internal static string InputNewDates {
            get {
                return ResourceManager.GetString("InputNewDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сад је касно за отказивање..
        /// </summary>
        internal static string LateCancel {
            get {
                return ResourceManager.GetString("LateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сад је касно за померање..
        /// </summary>
        internal static string LateReschedule {
            get {
                return ResourceManager.GetString("LateReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дужина Боравка:.
        /// </summary>
        internal static string LengthOfStay {
            get {
                return ResourceManager.GetString("LengthOfStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ниво Хитности Реновирања.
        /// </summary>
        internal static string LevelOfUrgencyForRenovation {
            get {
                return ResourceManager.GetString("LevelOfUrgencyForRenovation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локација.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одјава.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одјави Се (F12).
        /// </summary>
        internal static string LogoutF {
            get {
                return ResourceManager.GetString("LogoutF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПДФ Извештај (CTRL+F2).
        /// </summary>
        internal static string MakePDF {
            get {
                return ResourceManager.GetString("MakePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Направи Захтев За Померај.
        /// </summary>
        internal static string MakeRescheduleRequest {
            get {
                return ResourceManager.GetString("MakeRescheduleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс Број Гостију.
        /// </summary>
        internal static string MaxNumberOfGuests {
            get {
                return ResourceManager.GetString("MaxNumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин Дана За Резервацију.
        /// </summary>
        internal static string MinDaysForReservation {
            get {
                return ResourceManager.GetString("MinDaysForReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назив.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нема слободних у траженом опсегу. Препоруке излистане..
        /// </summary>
        internal static string NAS {
            get {
                return ResourceManager.GetString("NAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број Коментара.
        /// </summary>
        internal static string NOC {
            get {
                return ResourceManager.GetString("NOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказане Резервације.
        /// </summary>
        internal static string NotCncCb {
            get {
                return ResourceManager.GetString("NotCncCb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број Гостију:.
        /// </summary>
        internal static string NumberOfGuests {
            get {
                return ResourceManager.GetString("NumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Други Форуми:.
        /// </summary>
        internal static string OForums {
            get {
                return ResourceManager.GetString("OForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвори Форум (CTRL+F1).
        /// </summary>
        internal static string OpenForumF {
            get {
                return ResourceManager.GetString("OpenForumF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отвори Форум (F1).
        /// </summary>
        internal static string OpenForumFF {
            get {
                return ResourceManager.GetString("OpenForumFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обичан Гост.
        /// </summary>
        internal static string OrdinaryGuest {
            get {
                return ResourceManager.GetString("OrdinaryGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обичан Гост:.
        /// </summary>
        internal static string OrdinaryGuestD {
            get {
                return ResourceManager.GetString("OrdinaryGuestD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Постајете Супер Гост ако имате најмање 10 резервација у току године. Супер Гост добија 5 поена за попуст која могу бити употребљена на резервације у току годину дана. Један поен се троши после сваке резервације..
        /// </summary>
        internal static string Otxt1 {
            get {
                return ResourceManager.GetString("Otxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервација током прошле године: .
        /// </summary>
        internal static string Otxt2 {
            get {
                return ResourceManager.GetString("Otxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментар Власника.
        /// </summary>
        internal static string OwnerComment {
            get {
                return ResourceManager.GetString("OwnerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коректност Власника:.
        /// </summary>
        internal static string OwnerCorrectness {
            get {
                return ResourceManager.GetString("OwnerCorrectness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изаберите ниво хитности..
        /// </summary>
        internal static string PickUrgencyLevel {
            get {
                return ResourceManager.GetString("PickUrgencyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментариши (F1).
        /// </summary>
        internal static string PostCommentF {
            get {
                return ResourceManager.GetString("PostCommentF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Садржај Објаве:.
        /// </summary>
        internal static string PostContent {
            get {
                return ResourceManager.GetString("PostContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени Корисничко Име.
        /// </summary>
        internal static string ProfileB1 {
            get {
                return ResourceManager.GetString("ProfileB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени Шифру.
        /// </summary>
        internal static string ProfileB2 {
            get {
                return ResourceManager.GetString("ProfileB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промени Профилну Слику.
        /// </summary>
        internal static string ProfileB3 {
            get {
                return ResourceManager.GetString("ProfileB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Веома Прљаво.
        /// </summary>
        internal static string R11 {
            get {
                return ResourceManager.GetString("R11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Прљаво.
        /// </summary>
        internal static string R12 {
            get {
                return ResourceManager.GetString("R12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Донекле Чисто.
        /// </summary>
        internal static string R13 {
            get {
                return ResourceManager.GetString("R13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Чисто.
        /// </summary>
        internal static string R14 {
            get {
                return ResourceManager.GetString("R14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Веома Чисто.
        /// </summary>
        internal static string R15 {
            get {
                return ResourceManager.GetString("R15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Неприхватљива.
        /// </summary>
        internal static string R21 {
            get {
                return ResourceManager.GetString("R21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Лоша.
        /// </summary>
        internal static string R22 {
            get {
                return ResourceManager.GetString("R22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 Просечна.
        /// </summary>
        internal static string R23 {
            get {
                return ResourceManager.GetString("R23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Добра.
        /// </summary>
        internal static string R24 {
            get {
                return ResourceManager.GetString("R24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 Одлична.
        /// </summary>
        internal static string R25 {
            get {
                return ResourceManager.GetString("R25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нема потребе за реновирањем.
        /// </summary>
        internal static string R30 {
            get {
                return ResourceManager.GetString("R30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Било би лепо реновирати неке ситнице, али све функционише како треба и без тога.
        /// </summary>
        internal static string R31 {
            get {
                return ResourceManager.GetString("R31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Мале замерке на смештај које када би се уклониле би га учиниле савршеним.
        /// </summary>
        internal static string R32 {
            get {
                return ResourceManager.GetString("R32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Неколико ствари које су бап засметале би трбало реновирати.
        /// </summary>
        internal static string R33 {
            get {
                return ResourceManager.GetString("R33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Има доста лоших ствари и реновирање је стварно неопходно.
        /// </summary>
        internal static string R34 {
            get {
                return ResourceManager.GetString("R34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Смештај је у јако лошем стању и не вреди га уопште изнајмљивати уколико се не реновира.
        /// </summary>
        internal static string R35 {
            get {
                return ResourceManager.GetString("R35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опсег Датума:.
        /// </summary>
        internal static string RangePDF {
            get {
                return ResourceManager.GetString("RangePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обриши (F1).
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реновирано.
        /// </summary>
        internal static string Renovated {
            get {
                return ResourceManager.GetString("Renovated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Препорука За Реновирање.
        /// </summary>
        internal static string RenovationRecommendation {
            get {
                return ResourceManager.GetString("RenovationRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затражи Померај (F2).
        /// </summary>
        internal static string RequestRescheduleF {
            get {
                return ResourceManager.GetString("RequestRescheduleF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Захтев послат..
        /// </summary>
        internal static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервација Смештаја.
        /// </summary>
        internal static string ReserveAccommodation {
            get {
                return ResourceManager.GetString("ReserveAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервиши (F2).
        /// </summary>
        internal static string ReserveF {
            get {
                return ResourceManager.GetString("ReserveF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцени.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцени (F6).
        /// </summary>
        internal static string ReviewF {
            get {
                return ResourceManager.GetString("ReviewF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцени (F1).
        /// </summary>
        internal static string ReviewFa {
            get {
                return ResourceManager.GetString("ReviewFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцене о Вама.
        /// </summary>
        internal static string ReviewsAboutYou {
            get {
                return ResourceManager.GetString("ReviewsAboutYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оцена послата..
        /// </summary>
        internal static string RS {
            get {
                return ResourceManager.GetString("RS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одабери Државу и Град:.
        /// </summary>
        internal static string SCC {
            get {
                return ResourceManager.GetString("SCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Претражи (F4).
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Претрага Смештаја.
        /// </summary>
        internal static string SearchAccommodation {
            get {
                return ResourceManager.GetString("SearchAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Претражи (F1).
        /// </summary>
        internal static string SearchF {
            get {
                return ResourceManager.GetString("SearchF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одабрани Форум.
        /// </summary>
        internal static string SelForum {
            get {
                return ResourceManager.GetString("SelForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошаљи Захтев (F1).
        /// </summary>
        internal static string SendRequestF {
            get {
                return ResourceManager.GetString("SendRequestF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укупан број резервација: .
        /// </summary>
        internal static string Stat1 {
            get {
                return ResourceManager.GetString("Stat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to null.
        /// </summary>
        internal static string Stat2 {
            get {
                return ResourceManager.GetString("Stat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чистоћа: .
        /// </summary>
        internal static string Stat3 {
            get {
                return ResourceManager.GetString("Stat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поштовање правила: .
        /// </summary>
        internal static string Stat4 {
            get {
                return ResourceManager.GetString("Stat4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус Захтева Помераја.
        /// </summary>
        internal static string StatusOfRescheduleRequests {
            get {
                return ResourceManager.GetString("StatusOfRescheduleRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поена преостало: .
        /// </summary>
        internal static string Stxt1 {
            get {
                return ResourceManager.GetString("Stxt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум истека: .
        /// </summary>
        internal static string Stxt2 {
            get {
                return ResourceManager.GetString("Stxt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резервација у тренутном периоду: .
        /// </summary>
        internal static string Stxt3 {
            get {
                return ResourceManager.GetString("Stxt3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да би сте остали Супер Гост, морате имати бар 10 резервација до датума истека. Поени се бришу на датуму истека..
        /// </summary>
        internal static string Stxt4 {
            get {
                return ResourceManager.GetString("Stxt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошаљи Оцену (F1).
        /// </summary>
        internal static string SubmitReviewF {
            get {
                return ResourceManager.GetString("SubmitReviewF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супер Гост.
        /// </summary>
        internal static string SuperGuest {
            get {
                return ResourceManager.GetString("SuperGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супер Гост:.
        /// </summary>
        internal static string SuperGuestD {
            get {
                return ResourceManager.GetString("SuperGuestD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Супер Гост Поени:.
        /// </summary>
        internal static string SuperGuestPoints {
            get {
                return ResourceManager.GetString("SuperGuestPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наслов.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пута.
        /// </summary>
        internal static string TT {
            get {
                return ResourceManager.GetString("TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип Извештаја:.
        /// </summary>
        internal static string TypePDF {
            get {
                return ResourceManager.GetString("TypePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус Захтева (CTRL+F1).
        /// </summary>
        internal static string ViewRequestStatusF {
            get {
                return ResourceManager.GetString("ViewRequestStatusF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Твоје Резервације.
        /// </summary>
        internal static string YourReservations {
            get {
                return ResourceManager.GetString("YourReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Твоје Резервације (F5).
        /// </summary>
        internal static string YourReservationsF {
            get {
                return ResourceManager.GetString("YourReservationsF", resourceCulture);
            }
        }
    }
}
